// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BatchCartRequest
 */
export type BatchCartRequest = {
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * BatchDiscrepancyAction
 */
export type BatchDiscrepancyAction = {
    /**
     * Ids
     */
    ids?: Array<number> | null;
    /**
     * Path Prefix
     */
    path_prefix?: string | null;
};

/**
 * BatchResolveReport
 */
export type BatchResolveReport = {
    /**
     * Recovered Count
     */
    recovered_count: number;
    /**
     * Lost Count
     */
    lost_count: number;
    /**
     * Recovered Paths
     */
    recovered_paths: Array<string>;
    /**
     * Lost Paths
     */
    lost_paths: Array<string>;
    /**
     * Message
     */
    message: string;
};

/**
 * BatchTrackRequest
 */
export type BatchTrackRequest = {
    /**
     * Tracks
     */
    tracks?: Array<string>;
    /**
     * Untracks
     */
    untracks?: Array<string>;
};

/**
 * BrowseResponseSchema
 */
export type BrowseResponseSchema = {
    /**
     * Files
     */
    files: Array<FileItemSchema>;
    /**
     * Last Scan Time
     */
    last_scan_time?: string | null;
};

/**
 * CartFileItemSchema
 */
export type CartFileItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Mtime
     */
    mtime?: number | null;
    /**
     * Vulnerable
     */
    vulnerable?: boolean;
    /**
     * Selected
     */
    selected?: boolean;
    /**
     * Indeterminate
     */
    indeterminate?: boolean;
};

/**
 * CartItemSchema
 */
export type CartItemSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Type
     */
    type: string;
};

/**
 * CartTreeNodeSchema
 */
export type CartTreeNodeSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Has Children
     */
    has_children?: boolean;
};

/**
 * CloudCreateSchema
 *
 * Schema for creating S3-Compatible Cloud media.
 */
export type CloudCreateSchema = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type?: 's3_compat';
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Location Building
     */
    location_building?: string | null;
    /**
     * Location Room
     */
    location_room?: string | null;
    /**
     * Location Rack
     */
    location_rack?: string | null;
    /**
     * Location Slot
     */
    location_slot?: string | null;
    /**
     * Provider Template
     */
    provider_template: string;
    /**
     * Endpoint Url
     */
    endpoint_url: string;
    /**
     * Region
     */
    region: string;
    /**
     * Bucket Name
     */
    bucket_name: string;
    /**
     * Access Key Id
     */
    access_key_id: string;
    /**
     * Secret Access Key Name
     */
    secret_access_key_name?: string | null;
    /**
     * Path Style Access
     */
    path_style_access?: boolean;
    /**
     * Storage Class
     */
    storage_class?: string | null;
    /**
     * Max Part Size Mb
     */
    max_part_size_mb?: number;
    /**
     * Obfuscate Filenames
     */
    obfuscate_filenames?: boolean;
    /**
     * Encryption Secret Name
     */
    encryption_secret_name?: string | null;
};

/**
 * DashboardStatsSchema
 */
export type DashboardStatsSchema = {
    /**
     * Monitored Files Count
     */
    monitored_files_count: number;
    /**
     * Hashed Files Count
     */
    hashed_files_count: number;
    /**
     * Total Data Size
     */
    total_data_size: number;
    /**
     * Archived Data Size
     */
    archived_data_size: number;
    /**
     * Ignored Files Count
     */
    ignored_files_count: number;
    /**
     * Ignored Data Size
     */
    ignored_data_size: number;
    /**
     * Unprotected Files Count
     */
    unprotected_files_count: number;
    /**
     * Unprotected Data Size
     */
    unprotected_data_size: number;
    /**
     * Discrepancies Count
     */
    discrepancies_count: number;
    /**
     * Media Distribution
     */
    media_distribution: {
        [key: string]: number;
    };
    /**
     * Last Scan Time
     */
    last_scan_time: string | null;
    /**
     * Redundancy Ratio
     */
    redundancy_ratio: number;
};

/**
 * DirectoryCartRequest
 */
export type DirectoryCartRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * DiscrepancySchema
 */
export type DiscrepancySchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Mtime
     */
    mtime: string;
    /**
     * Last Seen Timestamp
     */
    last_seen_timestamp?: string | null;
    /**
     * Sha256 Hash
     */
    sha256_hash?: string | null;
    /**
     * Is Deleted
     */
    is_deleted: boolean;
    /**
     * Has Versions
     */
    has_versions?: boolean;
};

/**
 * FileItemSchema
 */
export type FileItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Mtime
     */
    mtime?: number | null;
    /**
     * Ignored
     */
    ignored?: boolean;
    /**
     * Sha256 Hash
     */
    sha256_hash?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IgnoreHardwareRequest
 */
export type IgnoreHardwareRequest = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * ItemMetadataSchema
 */
export type ItemMetadataSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Size
     */
    size: number;
    /**
     * Mtime
     */
    mtime: string;
    /**
     * Last Seen Timestamp
     */
    last_seen_timestamp?: string | null;
    /**
     * Sha256 Hash
     */
    sha256_hash?: string | null;
    /**
     * Is Ignored
     */
    is_ignored?: boolean;
    /**
     * Is Deleted
     */
    is_deleted?: boolean;
    /**
     * Exists On Disk
     */
    exists_on_disk?: boolean | null;
    /**
     * Child Count
     */
    child_count?: number | null;
    /**
     * Selected
     */
    selected?: boolean;
    /**
     * Versions
     */
    versions?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Is Partially Archived
     */
    is_partially_archived?: boolean;
    /**
     * Archived Bytes
     */
    archived_bytes?: number;
};

/**
 * JobLogSchema
 */
export type JobLogSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Message
     */
    message: string;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * LtoTapeCreateSchema
 *
 * Schema for creating LTO Tape media.
 */
export type LtoTapeCreateSchema = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type?: 'lto_tape';
    /**
     * Capacity
     */
    capacity?: number | null;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Location Building
     */
    location_building?: string | null;
    /**
     * Location Room
     */
    location_room?: string | null;
    /**
     * Location Rack
     */
    location_rack?: string | null;
    /**
     * Location Slot
     */
    location_slot?: string | null;
    /**
     * Generation
     */
    generation?: string | null;
    /**
     * Worm
     */
    worm?: boolean;
    /**
     * Write Protected
     */
    write_protected?: boolean;
    /**
     * Compression
     */
    compression?: boolean;
    /**
     * Encryption Key Id
     */
    encryption_key_id?: string | null;
    /**
     * Cleaning Cartridge
     */
    cleaning_cartridge?: boolean;
    /**
     * Encryption Secret Name
     */
    encryption_secret_name?: string | null;
    /**
     * Device Path
     */
    device_path?: string | null;
};

/**
 * ManifestMediaSchema
 */
export type ManifestMediaSchema = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * File Count
     */
    file_count: number;
    /**
     * Total Size
     */
    total_size: number;
};

/**
 * MediaSchema
 */
export type MediaSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Generation Tier
     */
    generation_tier?: string | null;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Bytes Used
     */
    bytes_used: number;
    /**
     * Status
     */
    status: string;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Location Building
     */
    location_building?: string | null;
    /**
     * Location Room
     */
    location_room?: string | null;
    /**
     * Location Rack
     */
    location_rack?: string | null;
    /**
     * Location Slot
     */
    location_slot?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Generation
     */
    generation?: string | null;
    /**
     * Worm
     */
    worm?: boolean;
    /**
     * Write Protected
     */
    write_protected?: boolean;
    /**
     * Compression
     */
    compression?: boolean;
    /**
     * Encryption Key Id
     */
    encryption_key_id?: string | null;
    /**
     * Cleaning Cartridge
     */
    cleaning_cartridge?: boolean;
    /**
     * Drive Model
     */
    drive_model?: string | null;
    /**
     * Device Uuid
     */
    device_uuid?: string | null;
    /**
     * Is Ssd
     */
    is_ssd?: boolean;
    /**
     * Mount Path
     */
    mount_path?: string | null;
    /**
     * Filesystem Type
     */
    filesystem_type?: string | null;
    /**
     * Connection Interface
     */
    connection_interface?: string | null;
    /**
     * Encrypted
     */
    encrypted?: boolean;
    /**
     * Provider Template
     */
    provider_template?: string | null;
    /**
     * Endpoint Url
     */
    endpoint_url?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Bucket Name
     */
    bucket_name?: string | null;
    /**
     * Access Key Id
     */
    access_key_id?: string | null;
    /**
     * Secret Access Key Name
     */
    secret_access_key_name?: string | null;
    /**
     * Path Style Access
     */
    path_style_access?: boolean;
    /**
     * Storage Class
     */
    storage_class?: string | null;
    /**
     * Max Part Size Mb
     */
    max_part_size_mb?: number;
    /**
     * Obfuscate Filenames
     */
    obfuscate_filenames?: boolean;
    /**
     * Encryption Secret Name
     */
    encryption_secret_name?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Is Online
     */
    is_online?: boolean;
    /**
     * Is Identified
     */
    is_identified?: boolean;
    /**
     * Needs Registration
     */
    needs_registration?: boolean;
    /**
     * Priority Index
     */
    priority_index?: number;
    /**
     * Host Free Bytes
     */
    host_free_bytes?: number | null;
    /**
     * Host Total Bytes
     */
    host_total_bytes?: number | null;
    /**
     * Live Info
     */
    live_info?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MediaUpdateSchema
 *
 * Schema for updating media - all fields optional.
 */
export type MediaUpdateSchema = {
    /**
     * Status
     */
    status?: string | null;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Location Building
     */
    location_building?: string | null;
    /**
     * Location Room
     */
    location_room?: string | null;
    /**
     * Location Rack
     */
    location_rack?: string | null;
    /**
     * Location Slot
     */
    location_slot?: string | null;
    /**
     * Capacity
     */
    capacity?: number | null;
    /**
     * Generation
     */
    generation?: string | null;
    /**
     * Worm
     */
    worm?: boolean | null;
    /**
     * Write Protected
     */
    write_protected?: boolean | null;
    /**
     * Compression
     */
    compression?: boolean | null;
    /**
     * Encryption Key Id
     */
    encryption_key_id?: string | null;
    /**
     * Cleaning Cartridge
     */
    cleaning_cartridge?: boolean | null;
    /**
     * Drive Model
     */
    drive_model?: string | null;
    /**
     * Device Uuid
     */
    device_uuid?: string | null;
    /**
     * Is Ssd
     */
    is_ssd?: boolean | null;
    /**
     * Mount Path
     */
    mount_path?: string | null;
    /**
     * Filesystem Type
     */
    filesystem_type?: string | null;
    /**
     * Connection Interface
     */
    connection_interface?: string | null;
    /**
     * Encrypted
     */
    encrypted?: boolean | null;
    /**
     * Provider Template
     */
    provider_template?: string | null;
    /**
     * Endpoint Url
     */
    endpoint_url?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Bucket Name
     */
    bucket_name?: string | null;
    /**
     * Access Key Id
     */
    access_key_id?: string | null;
    /**
     * Secret Access Key Name
     */
    secret_access_key_name?: string | null;
    /**
     * Path Style Access
     */
    path_style_access?: boolean | null;
    /**
     * Storage Class
     */
    storage_class?: string | null;
    /**
     * Max Part Size Mb
     */
    max_part_size_mb?: number | null;
    /**
     * Obfuscate Filenames
     */
    obfuscate_filenames?: boolean | null;
    /**
     * Encryption Secret Name
     */
    encryption_secret_name?: string | null;
};

/**
 * OfflineHddCreateSchema
 *
 * Schema for creating Offline HDD media.
 */
export type OfflineHddCreateSchema = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type?: 'local_hdd';
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Location Building
     */
    location_building?: string | null;
    /**
     * Location Room
     */
    location_room?: string | null;
    /**
     * Location Rack
     */
    location_rack?: string | null;
    /**
     * Location Slot
     */
    location_slot?: string | null;
    /**
     * Drive Model
     */
    drive_model?: string | null;
    /**
     * Device Uuid
     */
    device_uuid?: string | null;
    /**
     * Is Ssd
     */
    is_ssd?: boolean;
    /**
     * Mount Path
     */
    mount_path?: string | null;
    /**
     * Filesystem Type
     */
    filesystem_type?: string | null;
    /**
     * Connection Interface
     */
    connection_interface?: string | null;
    /**
     * Encrypted
     */
    encrypted?: boolean;
    /**
     * Encryption Key Id
     */
    encryption_key_id?: string | null;
    /**
     * Encryption Secret Name
     */
    encryption_secret_name?: string | null;
};

/**
 * ReorderMediaRequest
 */
export type ReorderMediaRequest = {
    /**
     * Media Ids
     */
    media_ids: Array<number>;
};

/**
 * RestoreManifestSchema
 */
export type RestoreManifestSchema = {
    /**
     * Total Files
     */
    total_files: number;
    /**
     * Total Size
     */
    total_size: number;
    /**
     * Media Required
     */
    media_required: Array<ManifestMediaSchema>;
};

/**
 * RestoreTriggerRequest
 */
export type RestoreTriggerRequest = {
    /**
     * Destination Path
     */
    destination_path: string;
};

/**
 * ScanStatusSchema
 */
export type ScanStatusSchema = {
    /**
     * Is Running
     */
    is_running: boolean;
    /**
     * Files Processed
     */
    files_processed: number;
    /**
     * Files Hashed
     */
    files_hashed: number;
    /**
     * Files New
     */
    files_new: number;
    /**
     * Files Modified
     */
    files_modified: number;
    /**
     * Files Missing
     */
    files_missing: number;
    /**
     * Total Files Found
     */
    total_files_found: number;
    /**
     * Current Path
     */
    current_path: string;
    /**
     * Is Throttled
     */
    is_throttled: boolean;
    /**
     * Hashing Speed
     */
    hashing_speed: string;
    /**
     * Last Run Time
     */
    last_run_time?: string | null;
};

/**
 * SecretCreateRequest
 */
export type SecretCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value: string;
};

/**
 * SecretDeleteRequest
 */
export type SecretDeleteRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * SettingSchema
 */
export type SettingSchema = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * StagingInfoSchema
 */
export type StagingInfoSchema = {
    /**
     * Path
     */
    path: string;
    /**
     * Total Bytes
     */
    total_bytes: number;
    /**
     * Used Bytes
     */
    used_bytes: number;
    /**
     * Free Bytes
     */
    free_bytes: number;
};

/**
 * StorageProviderSchema
 */
export type StorageProviderSchema = {
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Capabilities
     */
    capabilities: {
        [key: string]: boolean;
    };
    /**
     * Config Schema
     */
    config_schema: {
        [key: string]: unknown;
    };
};

/**
 * TestExclusionsRequest
 */
export type TestExclusionsRequest = {
    /**
     * Patterns
     */
    patterns: string;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * TestExclusionsResponse
 */
export type TestExclusionsResponse = {
    /**
     * Total Files
     */
    total_files: number;
    /**
     * Total Size
     */
    total_size: number;
    /**
     * Matched Count
     */
    matched_count: number;
    /**
     * Matched Size
     */
    matched_size: number;
    /**
     * Sample
     */
    sample: Array<FileItemSchema>;
};

/**
 * TestNotificationRequest
 */
export type TestNotificationRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * TreeNodeSchema
 */
export type TreeNodeSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Has Children
     */
    has_children?: boolean;
    /**
     * Children
     */
    children?: Array<TreeNodeSchema>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * JobSchema
 */
export type AppApiBackupsJobSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
};

/**
 * JobSchema
 */
export type AppApiCommonJobSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Current Task
     */
    current_task?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Latest Log
     */
    latest_log?: string | null;
};

export type ResetTestEnvironmentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/test/reset';
};

export type ResetTestEnvironmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/dashboard/stats';
};

export type GetDashboardStatsResponses = {
    /**
     * Successful Response
     */
    200: DashboardStatsSchema;
};

export type GetDashboardStatsResponse = GetDashboardStatsResponses[keyof GetDashboardStatsResponses];

export type GetStagingInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/staging/info';
};

export type GetStagingInfoResponses = {
    /**
     * Successful Response
     */
    200: StagingInfoSchema;
};

export type GetStagingInfoResponse = GetStagingInfoResponses[keyof GetStagingInfoResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/system/jobs';
};

export type ListJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Response List Jobs
     *
     * Successful Response
     */
    200: Array<AppApiCommonJobSchema>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/jobs/count';
};

export type GetJobCountResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetJobStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/jobs/stats';
};

export type GetJobStatsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/jobs/stream';
};

export type StreamJobsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/system/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: AppApiCommonJobSchema;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type GetJobLogsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/system/jobs/{job_id}/logs';
};

export type GetJobLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobLogsError = GetJobLogsErrors[keyof GetJobLogsErrors];

export type GetJobLogsResponses = {
    /**
     * Response Get Job Logs
     *
     * Successful Response
     */
    200: Array<JobLogSchema>;
};

export type GetJobLogsResponse = GetJobLogsResponses[keyof GetJobLogsResponses];

export type CancelJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/system/jobs/{job_id}/cancel';
};

export type CancelJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobError = CancelJobErrors[keyof CancelJobErrors];

export type CancelJobResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RetryJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/system/jobs/{job_id}/retry';
};

export type RetryJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryJobError = RetryJobErrors[keyof RetryJobErrors];

export type RetryJobResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerScanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/scan';
};

export type TriggerScanResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerIndexingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/index/hash';
};

export type TriggerIndexingResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetScanStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/scan/status';
};

export type GetScanStatusResponses = {
    /**
     * Successful Response
     */
    200: ScanStatusSchema;
};

export type GetScanStatusResponse = GetScanStatusResponses[keyof GetScanStatusResponses];

export type StreamScanStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/scan/stream';
};

export type StreamScanStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilesystemBrowseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/system/browse';
};

export type FilesystemBrowseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesystemBrowseError = FilesystemBrowseErrors[keyof FilesystemBrowseErrors];

export type FilesystemBrowseResponses = {
    /**
     * Successful Response
     */
    200: BrowseResponseSchema;
};

export type FilesystemBrowseResponse = FilesystemBrowseResponses[keyof FilesystemBrowseResponses];

export type FilesystemSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Path
         */
        path?: string | null;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
    };
    url: '/system/search';
};

export type FilesystemSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesystemSearchError = FilesystemSearchErrors[keyof FilesystemSearchErrors];

export type FilesystemSearchResponses = {
    /**
     * Response Filesystem Search
     *
     * Successful Response
     */
    200: Array<FileItemSchema>;
};

export type FilesystemSearchResponse = FilesystemSearchResponses[keyof FilesystemSearchResponses];

export type BatchTrackData = {
    body: BatchTrackRequest;
    path?: never;
    query?: never;
    url: '/system/track/batch';
};

export type BatchTrackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchTrackError = BatchTrackErrors[keyof BatchTrackErrors];

export type BatchTrackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/settings';
};

export type GetSettingsResponses = {
    /**
     * Response Get Settings
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: SettingSchema;
    path?: never;
    query?: never;
    url: '/system/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestExclusionsData = {
    body: TestExclusionsRequest;
    path?: never;
    query?: never;
    url: '/system/settings/test-exclusions';
};

export type TestExclusionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestExclusionsError = TestExclusionsErrors[keyof TestExclusionsErrors];

export type TestExclusionsResponses = {
    /**
     * Successful Response
     */
    200: TestExclusionsResponse;
};

export type TestExclusionsResponse2 = TestExclusionsResponses[keyof TestExclusionsResponses];

export type DownloadExclusionReportData = {
    body: TestExclusionsRequest;
    path?: never;
    query?: never;
    url: '/system/settings/test-exclusions/download';
};

export type DownloadExclusionReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadExclusionReportError = DownloadExclusionReportErrors[keyof DownloadExclusionReportErrors];

export type DownloadExclusionReportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteSecretData = {
    body: SecretDeleteRequest;
    path?: never;
    query?: never;
    url: '/system/secrets';
};

export type DeleteSecretErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSecretError = DeleteSecretErrors[keyof DeleteSecretErrors];

export type DeleteSecretResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListSecretsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/secrets';
};

export type ListSecretsResponses = {
    /**
     * Response List Secrets
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListSecretsResponse = ListSecretsResponses[keyof ListSecretsResponses];

export type CreateSecretData = {
    body: SecretCreateRequest;
    path?: never;
    query?: never;
    url: '/system/secrets';
};

export type CreateSecretErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSecretError = CreateSecretErrors[keyof CreateSecretErrors];

export type CreateSecretResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSecretData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/system/secrets/{name}';
};

export type GetSecretErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSecretError = GetSecretErrors[keyof GetSecretErrors];

export type GetSecretResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestNotificationData = {
    body: TestNotificationRequest;
    path?: never;
    query?: never;
    url: '/system/notifications/test';
};

export type TestNotificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestNotificationError = TestNotificationErrors[keyof TestNotificationErrors];

export type TestNotificationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDirectoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/system/ls';
};

export type ListDirectoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDirectoriesError = ListDirectoriesErrors[keyof ListDirectoriesErrors];

export type ListDirectoriesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DiscoverHardwareData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/hardware/discover';
};

export type DiscoverHardwareResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IgnoreHardwareData = {
    body: IgnoreHardwareRequest;
    path?: never;
    query?: never;
    url: '/system/hardware/ignore';
};

export type IgnoreHardwareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IgnoreHardwareError = IgnoreHardwareErrors[keyof IgnoreHardwareErrors];

export type IgnoreHardwareResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/database/export';
};

export type ExportDatabaseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportDatabaseData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File
         */
        file: unknown;
    };
    url: '/system/database/import';
};

export type ImportDatabaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportDatabaseError = ImportDatabaseErrors[keyof ImportDatabaseErrors];

export type ImportDatabaseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilesystemTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/system/tree';
};

export type FilesystemTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesystemTreeError = FilesystemTreeErrors[keyof FilesystemTreeErrors];

export type FilesystemTreeResponses = {
    /**
     * Response Filesystem Tree
     *
     * Successful Response
     */
    200: Array<TreeNodeSchema>;
};

export type FilesystemTreeResponse = FilesystemTreeResponses[keyof FilesystemTreeResponses];

export type ListDiscrepanciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/discrepancies';
};

export type ListDiscrepanciesResponses = {
    /**
     * Response List Discrepancies
     *
     * Successful Response
     */
    200: Array<DiscrepancySchema>;
};

export type ListDiscrepanciesResponse = ListDiscrepanciesResponses[keyof ListDiscrepanciesResponses];

export type BatchConfirmDiscrepanciesData = {
    body: BatchDiscrepancyAction;
    path?: never;
    query?: never;
    url: '/system/discrepancies/batch/confirm';
};

export type BatchConfirmDiscrepanciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchConfirmDiscrepanciesError = BatchConfirmDiscrepanciesErrors[keyof BatchConfirmDiscrepanciesErrors];

export type BatchConfirmDiscrepanciesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BatchDismissDiscrepanciesData = {
    body: BatchDiscrepancyAction;
    path?: never;
    query?: never;
    url: '/system/discrepancies/batch/dismiss';
};

export type BatchDismissDiscrepanciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchDismissDiscrepanciesError = BatchDismissDiscrepanciesErrors[keyof BatchDismissDiscrepanciesErrors];

export type BatchDismissDiscrepanciesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BatchDeleteDiscrepanciesData = {
    body: BatchDiscrepancyAction;
    path?: never;
    query?: never;
    url: '/system/discrepancies/batch/delete';
};

export type BatchDeleteDiscrepanciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchDeleteDiscrepanciesError = BatchDeleteDiscrepanciesErrors[keyof BatchDeleteDiscrepanciesErrors];

export type BatchDeleteDiscrepanciesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BatchResolveDiscrepanciesData = {
    body: BatchDiscrepancyAction;
    path?: never;
    query?: never;
    url: '/system/discrepancies/batch/resolve';
};

export type BatchResolveDiscrepanciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchResolveDiscrepanciesError = BatchResolveDiscrepanciesErrors[keyof BatchResolveDiscrepanciesErrors];

export type BatchResolveDiscrepanciesResponses = {
    /**
     * Successful Response
     */
    200: BatchResolveReport;
};

export type BatchResolveDiscrepanciesResponse = BatchResolveDiscrepanciesResponses[keyof BatchResolveDiscrepanciesResponses];

export type ConfirmDiscrepancyData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/system/discrepancies/{file_id}/confirm';
};

export type ConfirmDiscrepancyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmDiscrepancyError = ConfirmDiscrepancyErrors[keyof ConfirmDiscrepancyErrors];

export type ConfirmDiscrepancyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DismissDiscrepancyData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/system/discrepancies/{file_id}/dismiss';
};

export type DismissDiscrepancyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DismissDiscrepancyError = DismissDiscrepancyErrors[keyof DismissDiscrepancyErrors];

export type DismissDiscrepancyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UndoDismissDiscrepancyData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/system/discrepancies/{file_id}/undo-dismiss';
};

export type UndoDismissDiscrepancyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UndoDismissDiscrepancyError = UndoDismissDiscrepancyErrors[keyof UndoDismissDiscrepancyErrors];

export type UndoDismissDiscrepancyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteDiscrepancyData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/system/discrepancies/{file_id}';
};

export type DeleteDiscrepancyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDiscrepancyError = DeleteDiscrepancyErrors[keyof DeleteDiscrepancyErrors];

export type DeleteDiscrepancyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDiscrepancyTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         *
         * Root path to get tree for
         */
        path?: string | null;
    };
    url: '/system/discrepancies/tree';
};

export type GetDiscrepancyTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiscrepancyTreeError = GetDiscrepancyTreeErrors[keyof GetDiscrepancyTreeErrors];

export type GetDiscrepancyTreeResponses = {
    /**
     * Response Get Discrepancy Tree
     *
     * Successful Response
     */
    200: Array<TreeNodeSchema>;
};

export type GetDiscrepancyTreeResponse = GetDiscrepancyTreeResponses[keyof GetDiscrepancyTreeResponses];

export type BrowseDiscrepanciesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         *
         * Directory path to browse
         */
        path?: string | null;
    };
    url: '/system/discrepancies/browse';
};

export type BrowseDiscrepanciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowseDiscrepanciesError = BrowseDiscrepanciesErrors[keyof BrowseDiscrepanciesErrors];

export type BrowseDiscrepanciesResponses = {
    /**
     * Response Browse Discrepancies
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BrowseDiscrepanciesResponse = BrowseDiscrepanciesResponses[keyof BrowseDiscrepanciesResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/providers';
};

export type ListProvidersResponses = {
    /**
     * Response List Providers
     *
     * Successful Response
     */
    200: Array<StorageProviderSchema>;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type ListMediaData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Refresh
         */
        refresh?: boolean;
    };
    url: '/inventory/media';
};

export type ListMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMediaError = ListMediaErrors[keyof ListMediaErrors];

export type ListMediaResponses = {
    /**
     * Response List Media
     *
     * Successful Response
     */
    200: Array<MediaSchema>;
};

export type ListMediaResponse = ListMediaResponses[keyof ListMediaResponses];

export type CreateMediaData = {
    /**
     * Request Data
     */
    body: LtoTapeCreateSchema | OfflineHddCreateSchema | CloudCreateSchema;
    path?: never;
    query?: never;
    url: '/inventory/media';
};

export type CreateMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMediaError = CreateMediaErrors[keyof CreateMediaErrors];

export type CreateMediaResponses = {
    /**
     * Successful Response
     */
    200: MediaSchema;
};

export type CreateMediaResponse = CreateMediaResponses[keyof CreateMediaResponses];

export type ReorderMediaData = {
    body: ReorderMediaRequest;
    path?: never;
    query?: never;
    url: '/inventory/media/reorder';
};

export type ReorderMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderMediaError = ReorderMediaErrors[keyof ReorderMediaErrors];

export type ReorderMediaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMediaData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/inventory/media/{media_id}';
};

export type DeleteMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMediaError = DeleteMediaErrors[keyof DeleteMediaErrors];

export type DeleteMediaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateMediaData = {
    body: MediaUpdateSchema;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/inventory/media/{media_id}';
};

export type UpdateMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMediaError = UpdateMediaErrors[keyof UpdateMediaErrors];

export type UpdateMediaResponses = {
    /**
     * Successful Response
     */
    200: MediaSchema;
};

export type UpdateMediaResponse = UpdateMediaResponses[keyof UpdateMediaResponses];

export type InitializeMediaData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/inventory/media/{media_id}/initialize';
};

export type InitializeMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitializeMediaError = InitializeMediaErrors[keyof InitializeMediaErrors];

export type InitializeMediaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAnalyticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/insights';
};

export type GetAnalyticsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTreemapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/directories';
};

export type GetTreemapResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DetectMediaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/detect';
};

export type DetectMediaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveBrowseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/archive/browse';
};

export type ArchiveBrowseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveBrowseError = ArchiveBrowseErrors[keyof ArchiveBrowseErrors];

export type ArchiveBrowseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/archive/search';
};

export type ArchiveSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveSearchError = ArchiveSearchErrors[keyof ArchiveSearchErrors];

export type ArchiveSearchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArchiveTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/archive/tree';
};

export type ArchiveTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveTreeError = ArchiveTreeErrors[keyof ArchiveTreeErrors];

export type ArchiveTreeResponses = {
    /**
     * Response Archive Tree
     *
     * Successful Response
     */
    200: Array<TreeNodeSchema>;
};

export type ArchiveTreeResponse = ArchiveTreeResponses[keyof ArchiveTreeResponses];

export type ArchiveMetadataData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/archive/metadata';
};

export type ArchiveMetadataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveMetadataError = ArchiveMetadataErrors[keyof ArchiveMetadataErrors];

export type ArchiveMetadataResponses = {
    /**
     * Successful Response
     */
    200: ItemMetadataSchema;
};

export type ArchiveMetadataResponse = ArchiveMetadataResponses[keyof ArchiveMetadataResponses];

export type TriggerAutoBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups/trigger/auto';
};

export type TriggerAutoBackupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerBackupData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/backups/trigger/{media_id}';
};

export type TriggerBackupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerBackupError = TriggerBackupErrors[keyof TriggerBackupErrors];

export type TriggerBackupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListBackupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups/';
};

export type ListBackupsResponses = {
    /**
     * Response List Backups
     *
     * Successful Response
     */
    200: Array<AppApiBackupsJobSchema>;
};

export type ListBackupsResponse = ListBackupsResponses[keyof ListBackupsResponses];

export type GetRestoreQueueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/queue';
};

export type GetRestoreQueueResponses = {
    /**
     * Response Get Restore Queue
     *
     * Successful Response
     */
    200: Array<CartItemSchema>;
};

export type GetRestoreQueueResponse = GetRestoreQueueResponses[keyof GetRestoreQueueResponses];

export type ClearRestoreQueueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/queue/clear';
};

export type ClearRestoreQueueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddDirectoryToRestoreQueueData = {
    body: DirectoryCartRequest;
    path?: never;
    query?: never;
    url: '/restores/queue/directory';
};

export type AddDirectoryToRestoreQueueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDirectoryToRestoreQueueError = AddDirectoryToRestoreQueueErrors[keyof AddDirectoryToRestoreQueueErrors];

export type AddDirectoryToRestoreQueueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddFileToRestoreQueueData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/restores/queue/file/{file_id}';
};

export type AddFileToRestoreQueueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddFileToRestoreQueueError = AddFileToRestoreQueueErrors[keyof AddFileToRestoreQueueErrors];

export type AddFileToRestoreQueueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BatchAddToRestoreQueueData = {
    body: BatchCartRequest;
    path?: never;
    query?: never;
    url: '/restores/queue/batch';
};

export type BatchAddToRestoreQueueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchAddToRestoreQueueError = BatchAddToRestoreQueueErrors[keyof BatchAddToRestoreQueueErrors];

export type BatchAddToRestoreQueueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveFromRestoreQueueData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/restores/queue/item/{item_id}';
};

export type RemoveFromRestoreQueueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveFromRestoreQueueError = RemoveFromRestoreQueueErrors[keyof RemoveFromRestoreQueueErrors];

export type RemoveFromRestoreQueueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRestoreManifestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/manifest';
};

export type GetRestoreManifestResponses = {
    /**
     * Successful Response
     */
    200: RestoreManifestSchema;
};

export type GetRestoreManifestResponse = GetRestoreManifestResponses[keyof GetRestoreManifestResponses];

export type TriggerRestoreData = {
    body: RestoreTriggerRequest;
    path?: never;
    query?: never;
    url: '/restores/trigger';
};

export type TriggerRestoreErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerRestoreError = TriggerRestoreErrors[keyof TriggerRestoreErrors];

export type TriggerRestoreResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BrowseRestoreQueueData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/restores/queue/browse';
};

export type BrowseRestoreQueueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowseRestoreQueueError = BrowseRestoreQueueErrors[keyof BrowseRestoreQueueErrors];

export type BrowseRestoreQueueResponses = {
    /**
     * Response Browse Restore Queue
     *
     * Successful Response
     */
    200: Array<CartFileItemSchema>;
};

export type BrowseRestoreQueueResponse = BrowseRestoreQueueResponses[keyof BrowseRestoreQueueResponses];

export type GetRestoreQueueTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/restores/queue/tree';
};

export type GetRestoreQueueTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRestoreQueueTreeError = GetRestoreQueueTreeErrors[keyof GetRestoreQueueTreeErrors];

export type GetRestoreQueueTreeResponses = {
    /**
     * Response Get Restore Queue Tree
     *
     * Successful Response
     */
    200: Array<CartTreeNodeSchema>;
};

export type GetRestoreQueueTreeResponse = GetRestoreQueueTreeResponses[keyof GetRestoreQueueTreeResponses];

export type CheckHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type CheckHealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
