// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BatchTrackRequest
 */
export type BatchTrackRequest = {
    /**
     * Tracks
     */
    tracks?: Array<string>;
    /**
     * Untracks
     */
    untracks?: Array<string>;
};

/**
 * Body_import_database_system_database_import_post
 */
export type BodyImportDatabaseSystemDatabaseImportPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CartFileItemSchema
 */
export type CartFileItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Media
     */
    media?: Array<string>;
};

/**
 * CartItemSchema
 */
export type CartItemSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Media Identifiers
     */
    media_identifiers: Array<string>;
};

/**
 * CartTreeNodeSchema
 */
export type CartTreeNodeSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Has Children
     */
    has_children?: boolean;
};

/**
 * DashboardStatsSchema
 */
export type DashboardStatsSchema = {
    /**
     * Total Files Indexed
     */
    total_files_indexed: number;
    /**
     * Total Data Size
     */
    total_data_size: number;
    /**
     * Tracked Paths Count
     */
    tracked_paths_count: number;
    /**
     * Unprotected Files Count
     */
    unprotected_files_count: number;
    /**
     * Unprotected Data Size
     */
    unprotected_data_size: number;
    /**
     * Ignored Files Count
     */
    ignored_files_count: number;
    /**
     * Ignored Data Size
     */
    ignored_data_size: number;
    /**
     * Redundancy Ratio
     */
    redundancy_ratio: number;
    /**
     * Last Scan Time
     */
    last_scan_time: string | null;
    /**
     * Media Distribution
     */
    media_distribution: {
        [key: string]: number;
    };
};

/**
 * DirectoryCartRequest
 */
export type DirectoryCartRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * FileVersionSchema
 */
export type FileVersionSchema = {
    /**
     * Media Identifier
     */
    media_identifier: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * File Number
     */
    file_number: string;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemMetadataSchema
 */
export type ItemMetadataSchema = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Mtime
     */
    mtime: number;
    /**
     * Last Seen Timestamp
     */
    last_seen_timestamp: string;
    /**
     * Sha256 Hash
     */
    sha256_hash?: string | null;
    /**
     * Versions
     */
    versions?: Array<FileVersionSchema>;
    /**
     * Child Count
     */
    child_count?: number | null;
    /**
     * Vulnerable
     */
    vulnerable?: boolean;
    /**
     * Selected
     */
    selected?: boolean;
    /**
     * Indeterminate
     */
    indeterminate?: boolean;
};

/**
 * JobSchema
 */
export type JobSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Current Task
     */
    current_task: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ManifestMediaRequirement
 */
export type ManifestMediaRequirement = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * File Count
     */
    file_count: number;
    /**
     * Total Size
     */
    total_size: number;
};

/**
 * MediaCreateSchema
 */
export type MediaCreateSchema = {
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Generation Tier
     */
    generation_tier?: string | null;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * MediaSchema
 */
export type MediaSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Generation Tier
     */
    generation_tier: string | null;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Bytes Used
     */
    bytes_used: number;
    /**
     * Location
     */
    location: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Is Online
     */
    is_online?: boolean;
    /**
     * Priority Index
     */
    priority_index?: number;
};

/**
 * MediaUpdateSchema
 */
export type MediaUpdateSchema = {
    /**
     * Status
     */
    status?: string | null;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ReorderMediaRequest
 */
export type ReorderMediaRequest = {
    /**
     * Media Ids
     */
    media_ids: Array<number>;
};

/**
 * RestoreManifestSchema
 */
export type RestoreManifestSchema = {
    /**
     * Total Files
     */
    total_files: number;
    /**
     * Total Size
     */
    total_size: number;
    /**
     * Media Required
     */
    media_required: Array<ManifestMediaRequirement>;
};

/**
 * RestoreRequest
 */
export type RestoreRequest = {
    /**
     * Destination
     */
    destination: string;
};

/**
 * ScanStatusSchema
 */
export type ScanStatusSchema = {
    /**
     * Is Running
     */
    is_running: boolean;
    /**
     * Files Processed
     */
    files_processed: number;
    /**
     * Files Hashed
     */
    files_hashed: number;
    /**
     * Total Files Found
     */
    total_files_found: number;
    /**
     * Current Path
     */
    current_path: string;
    /**
     * Last Run Time
     */
    last_run_time?: string | null;
};

/**
 * SettingSchema
 */
export type SettingSchema = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * TestNotificationRequest
 */
export type TestNotificationRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * TreeNodeSchema
 */
export type TreeNodeSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Has Children
     */
    has_children?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * FileItemSchema
 */
export type AppApiInventoryFileItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Mtime
     */
    mtime?: number | null;
    /**
     * Media
     */
    media?: Array<string>;
    /**
     * Vulnerable
     */
    vulnerable?: boolean;
    /**
     * Selected
     */
    selected?: boolean;
    /**
     * Indeterminate
     */
    indeterminate?: boolean;
};

/**
 * FileItemSchema
 */
export type AppApiSystemFileItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Mtime
     */
    mtime?: number | null;
    /**
     * Tracked
     */
    tracked?: boolean;
    /**
     * Ignored
     */
    ignored?: boolean;
};

export type GetDashboardStatsSystemDashboardStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/dashboard/stats';
};

export type GetDashboardStatsSystemDashboardStatsGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardStatsSchema;
};

export type GetDashboardStatsSystemDashboardStatsGetResponse = GetDashboardStatsSystemDashboardStatsGetResponses[keyof GetDashboardStatsSystemDashboardStatsGetResponses];

export type ListJobsSystemJobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/system/jobs';
};

export type ListJobsSystemJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsSystemJobsGetError = ListJobsSystemJobsGetErrors[keyof ListJobsSystemJobsGetErrors];

export type ListJobsSystemJobsGetResponses = {
    /**
     * Response List Jobs System Jobs Get
     *
     * Successful Response
     */
    200: Array<JobSchema>;
};

export type ListJobsSystemJobsGetResponse = ListJobsSystemJobsGetResponses[keyof ListJobsSystemJobsGetResponses];

export type CancelJobSystemJobsJobIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/system/jobs/{job_id}/cancel';
};

export type CancelJobSystemJobsJobIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobSystemJobsJobIdCancelPostError = CancelJobSystemJobsJobIdCancelPostErrors[keyof CancelJobSystemJobsJobIdCancelPostErrors];

export type CancelJobSystemJobsJobIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamJobsSystemJobsStreamGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/jobs/stream';
};

export type StreamJobsSystemJobsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerScanSystemScanPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/scan';
};

export type TriggerScanSystemScanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetScanStatusSystemScanStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/scan/status';
};

export type GetScanStatusSystemScanStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ScanStatusSchema;
};

export type GetScanStatusSystemScanStatusGetResponse = GetScanStatusSystemScanStatusGetResponses[keyof GetScanStatusSystemScanStatusGetResponses];

export type BrowsePathSystemBrowseGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/system/browse';
};

export type BrowsePathSystemBrowseGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowsePathSystemBrowseGetError = BrowsePathSystemBrowseGetErrors[keyof BrowsePathSystemBrowseGetErrors];

export type BrowsePathSystemBrowseGetResponses = {
    /**
     * Response Browse Path System Browse Get
     *
     * Successful Response
     */
    200: Array<AppApiSystemFileItemSchema>;
};

export type BrowsePathSystemBrowseGetResponse = BrowsePathSystemBrowseGetResponses[keyof BrowsePathSystemBrowseGetResponses];

export type SearchSystemSystemSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
    };
    url: '/system/search';
};

export type SearchSystemSystemSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSystemSystemSearchGetError = SearchSystemSystemSearchGetErrors[keyof SearchSystemSystemSearchGetErrors];

export type SearchSystemSystemSearchGetResponses = {
    /**
     * Response Search System System Search Get
     *
     * Successful Response
     */
    200: Array<AppApiSystemFileItemSchema>;
};

export type SearchSystemSystemSearchGetResponse = SearchSystemSystemSearchGetResponses[keyof SearchSystemSystemSearchGetResponses];

export type TrackBatchSystemTrackBatchPostData = {
    body: BatchTrackRequest;
    path?: never;
    query?: never;
    url: '/system/track/batch';
};

export type TrackBatchSystemTrackBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TrackBatchSystemTrackBatchPostError = TrackBatchSystemTrackBatchPostErrors[keyof TrackBatchSystemTrackBatchPostErrors];

export type TrackBatchSystemTrackBatchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSettingsSystemSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/settings';
};

export type GetSettingsSystemSettingsGetResponses = {
    /**
     * Response Get Settings System Settings Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetSettingsSystemSettingsGetResponse = GetSettingsSystemSettingsGetResponses[keyof GetSettingsSystemSettingsGetResponses];

export type UpdateSettingSystemSettingsPostData = {
    body: SettingSchema;
    path?: never;
    query?: never;
    url: '/system/settings';
};

export type UpdateSettingSystemSettingsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingSystemSettingsPostError = UpdateSettingSystemSettingsPostErrors[keyof UpdateSettingSystemSettingsPostErrors];

export type UpdateSettingSystemSettingsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestNotificationSystemNotificationsTestPostData = {
    body: TestNotificationRequest;
    path?: never;
    query?: never;
    url: '/system/notifications/test';
};

export type TestNotificationSystemNotificationsTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestNotificationSystemNotificationsTestPostError = TestNotificationSystemNotificationsTestPostErrors[keyof TestNotificationSystemNotificationsTestPostErrors];

export type TestNotificationSystemNotificationsTestPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportDatabaseSystemDatabaseExportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/database/export';
};

export type ExportDatabaseSystemDatabaseExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportDatabaseSystemDatabaseImportPostData = {
    body: BodyImportDatabaseSystemDatabaseImportPost;
    path?: never;
    query?: never;
    url: '/system/database/import';
};

export type ImportDatabaseSystemDatabaseImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportDatabaseSystemDatabaseImportPostError = ImportDatabaseSystemDatabaseImportPostErrors[keyof ImportDatabaseSystemDatabaseImportPostErrors];

export type ImportDatabaseSystemDatabaseImportPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTreeSystemTreeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/system/tree';
};

export type GetTreeSystemTreeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTreeSystemTreeGetError = GetTreeSystemTreeGetErrors[keyof GetTreeSystemTreeGetErrors];

export type GetTreeSystemTreeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListMediaInventoryMediaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/media';
};

export type ListMediaInventoryMediaGetResponses = {
    /**
     * Response List Media Inventory Media Get
     *
     * Successful Response
     */
    200: Array<MediaSchema>;
};

export type ListMediaInventoryMediaGetResponse = ListMediaInventoryMediaGetResponses[keyof ListMediaInventoryMediaGetResponses];

export type RegisterMediaInventoryMediaPostData = {
    body: MediaCreateSchema;
    path?: never;
    query?: never;
    url: '/inventory/media';
};

export type RegisterMediaInventoryMediaPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterMediaInventoryMediaPostError = RegisterMediaInventoryMediaPostErrors[keyof RegisterMediaInventoryMediaPostErrors];

export type RegisterMediaInventoryMediaPostResponses = {
    /**
     * Successful Response
     */
    200: MediaSchema;
};

export type RegisterMediaInventoryMediaPostResponse = RegisterMediaInventoryMediaPostResponses[keyof RegisterMediaInventoryMediaPostResponses];

export type ReorderMediaInventoryMediaReorderPostData = {
    body: ReorderMediaRequest;
    path?: never;
    query?: never;
    url: '/inventory/media/reorder';
};

export type ReorderMediaInventoryMediaReorderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderMediaInventoryMediaReorderPostError = ReorderMediaInventoryMediaReorderPostErrors[keyof ReorderMediaInventoryMediaReorderPostErrors];

export type ReorderMediaInventoryMediaReorderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMediaInventoryMediaMediaIdDeleteData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/inventory/media/{media_id}';
};

export type DeleteMediaInventoryMediaMediaIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMediaInventoryMediaMediaIdDeleteError = DeleteMediaInventoryMediaMediaIdDeleteErrors[keyof DeleteMediaInventoryMediaMediaIdDeleteErrors];

export type DeleteMediaInventoryMediaMediaIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateMediaInventoryMediaMediaIdPatchData = {
    body: MediaUpdateSchema;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/inventory/media/{media_id}';
};

export type UpdateMediaInventoryMediaMediaIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMediaInventoryMediaMediaIdPatchError = UpdateMediaInventoryMediaMediaIdPatchErrors[keyof UpdateMediaInventoryMediaMediaIdPatchErrors];

export type UpdateMediaInventoryMediaMediaIdPatchResponses = {
    /**
     * Successful Response
     */
    200: MediaSchema;
};

export type UpdateMediaInventoryMediaMediaIdPatchResponse = UpdateMediaInventoryMediaMediaIdPatchResponses[keyof UpdateMediaInventoryMediaMediaIdPatchResponses];

export type InitializeMediaInventoryMediaMediaIdInitializePostData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/inventory/media/{media_id}/initialize';
};

export type InitializeMediaInventoryMediaMediaIdInitializePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitializeMediaInventoryMediaMediaIdInitializePostError = InitializeMediaInventoryMediaMediaIdInitializePostErrors[keyof InitializeMediaInventoryMediaMediaIdInitializePostErrors];

export type InitializeMediaInventoryMediaMediaIdInitializePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BrowseIndexInventoryBrowseGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
    };
    url: '/inventory/browse';
};

export type BrowseIndexInventoryBrowseGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowseIndexInventoryBrowseGetError = BrowseIndexInventoryBrowseGetErrors[keyof BrowseIndexInventoryBrowseGetErrors];

export type BrowseIndexInventoryBrowseGetResponses = {
    /**
     * Response Browse Index Inventory Browse Get
     *
     * Successful Response
     */
    200: Array<AppApiInventoryFileItemSchema>;
};

export type BrowseIndexInventoryBrowseGetResponse = BrowseIndexInventoryBrowseGetResponses[keyof BrowseIndexInventoryBrowseGetResponses];

export type SearchIndexInventorySearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
    };
    url: '/inventory/search';
};

export type SearchIndexInventorySearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchIndexInventorySearchGetError = SearchIndexInventorySearchGetErrors[keyof SearchIndexInventorySearchGetErrors];

export type SearchIndexInventorySearchGetResponses = {
    /**
     * Response Search Index Inventory Search Get
     *
     * Successful Response
     */
    200: Array<AppApiInventoryFileItemSchema>;
};

export type SearchIndexInventorySearchGetResponse = SearchIndexInventorySearchGetResponses[keyof SearchIndexInventorySearchGetResponses];

export type GetIndexTreeInventoryTreeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
    };
    url: '/inventory/tree';
};

export type GetIndexTreeInventoryTreeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIndexTreeInventoryTreeGetError = GetIndexTreeInventoryTreeGetErrors[keyof GetIndexTreeInventoryTreeGetErrors];

export type GetIndexTreeInventoryTreeGetResponses = {
    /**
     * Response Get Index Tree Inventory Tree Get
     *
     * Successful Response
     */
    200: Array<TreeNodeSchema>;
};

export type GetIndexTreeInventoryTreeGetResponse = GetIndexTreeInventoryTreeGetResponses[keyof GetIndexTreeInventoryTreeGetResponses];

export type GetItemMetadataInventoryMetadataGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/inventory/metadata';
};

export type GetItemMetadataInventoryMetadataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemMetadataInventoryMetadataGetError = GetItemMetadataInventoryMetadataGetErrors[keyof GetItemMetadataInventoryMetadataGetErrors];

export type GetItemMetadataInventoryMetadataGetResponses = {
    /**
     * Successful Response
     */
    200: ItemMetadataSchema;
};

export type GetItemMetadataInventoryMetadataGetResponse = GetItemMetadataInventoryMetadataGetResponses[keyof GetItemMetadataInventoryMetadataGetResponses];

export type ListInventoryInventoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inventory/';
};

export type ListInventoryInventoryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerBackupBackupsTriggerMediaIdPostData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/backups/trigger/{media_id}';
};

export type TriggerBackupBackupsTriggerMediaIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerBackupBackupsTriggerMediaIdPostError = TriggerBackupBackupsTriggerMediaIdPostErrors[keyof TriggerBackupBackupsTriggerMediaIdPostErrors];

export type TriggerBackupBackupsTriggerMediaIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListBackupsBackupsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups/';
};

export type ListBackupsBackupsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerRestoreRestoresTriggerPostData = {
    body: RestoreRequest;
    path?: never;
    query?: never;
    url: '/restores/trigger';
};

export type TriggerRestoreRestoresTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerRestoreRestoresTriggerPostError = TriggerRestoreRestoresTriggerPostErrors[keyof TriggerRestoreRestoresTriggerPostErrors];

export type TriggerRestoreRestoresTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BrowseCartRestoresCartBrowseGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/restores/cart/browse';
};

export type BrowseCartRestoresCartBrowseGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowseCartRestoresCartBrowseGetError = BrowseCartRestoresCartBrowseGetErrors[keyof BrowseCartRestoresCartBrowseGetErrors];

export type BrowseCartRestoresCartBrowseGetResponses = {
    /**
     * Response Browse Cart Restores Cart Browse Get
     *
     * Successful Response
     */
    200: Array<CartFileItemSchema>;
};

export type BrowseCartRestoresCartBrowseGetResponse = BrowseCartRestoresCartBrowseGetResponses[keyof BrowseCartRestoresCartBrowseGetResponses];

export type GetCartTreeRestoresCartTreeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/restores/cart/tree';
};

export type GetCartTreeRestoresCartTreeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCartTreeRestoresCartTreeGetError = GetCartTreeRestoresCartTreeGetErrors[keyof GetCartTreeRestoresCartTreeGetErrors];

export type GetCartTreeRestoresCartTreeGetResponses = {
    /**
     * Response Get Cart Tree Restores Cart Tree Get
     *
     * Successful Response
     */
    200: Array<CartTreeNodeSchema>;
};

export type GetCartTreeRestoresCartTreeGetResponse = GetCartTreeRestoresCartTreeGetResponses[keyof GetCartTreeRestoresCartTreeGetResponses];

export type ListCartRestoresCartGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/cart';
};

export type ListCartRestoresCartGetResponses = {
    /**
     * Response List Cart Restores Cart Get
     *
     * Successful Response
     */
    200: Array<CartItemSchema>;
};

export type ListCartRestoresCartGetResponse = ListCartRestoresCartGetResponses[keyof ListCartRestoresCartGetResponses];

export type ClearCartRestoresCartClearPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/cart/clear';
};

export type ClearCartRestoresCartClearPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddDirectoryToCartRestoresCartDirectoryPostData = {
    body: DirectoryCartRequest;
    path?: never;
    query?: never;
    url: '/restores/cart/directory';
};

export type AddDirectoryToCartRestoresCartDirectoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDirectoryToCartRestoresCartDirectoryPostError = AddDirectoryToCartRestoresCartDirectoryPostErrors[keyof AddDirectoryToCartRestoresCartDirectoryPostErrors];

export type AddDirectoryToCartRestoresCartDirectoryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddToCartRestoresCartFileIdPostData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/restores/cart/{file_id}';
};

export type AddToCartRestoresCartFileIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddToCartRestoresCartFileIdPostError = AddToCartRestoresCartFileIdPostErrors[keyof AddToCartRestoresCartFileIdPostErrors];

export type AddToCartRestoresCartFileIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveFromCartRestoresCartItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/restores/cart/{item_id}';
};

export type RemoveFromCartRestoresCartItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveFromCartRestoresCartItemIdDeleteError = RemoveFromCartRestoresCartItemIdDeleteErrors[keyof RemoveFromCartRestoresCartItemIdDeleteErrors];

export type RemoveFromCartRestoresCartItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetManifestRestoresManifestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restores/manifest';
};

export type GetManifestRestoresManifestGetResponses = {
    /**
     * Successful Response
     */
    200: RestoreManifestSchema;
};

export type GetManifestRestoresManifestGetResponse = GetManifestRestoresManifestGetResponses[keyof GetManifestRestoresManifestGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
