"""add_media_priority

Revision ID: 1bed186f8732
Revises: 51c095df4615
Create Date: 2026-04-25 18:14:58.790448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bed186f8732"
down_revision: Union[str, Sequence[str], None] = "ac51f5e25832"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storage_media",
        sa.Column("priority_index", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage_media", "priority_index")
    # ### end Alembic commands ###
