"""sync_models

Revision ID: 5e867c5b4930
Revises: 193bb204c677
Create Date: 2026-04-23 19:10:26.093824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e867c5b4930"
down_revision: Union[str, Sequence[str], None] = "193bb204c677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "filesystem_state",
        sa.Column("is_indexed", sa.Boolean(), nullable=False, server_default="0"),
    )
    op.add_column(
        "filesystem_state",
        sa.Column("is_ignored", sa.Boolean(), nullable=False, server_default="0"),
    )
    op.add_column(
        "storage_media", sa.Column("extra_config", sa.String(), nullable=True)
    )

    # We must also create missing tables: TrackedSource, RestoreCart, Job, SystemSetting
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("current_task", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "restore_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filesystem_state_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["filesystem_state_id"],
            ["filesystem_state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tracked_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("is_directory", sa.Boolean(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracked_sources_path"), "tracked_sources", ["path"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_sources_path"), table_name="tracked_sources")
    op.drop_table("tracked_sources")
    op.drop_table("system_settings")
    op.drop_table("restore_cart")
    op.drop_table("jobs")

    op.drop_column("storage_media", "extra_config")
    op.drop_column("filesystem_state", "is_ignored")
    op.drop_column("filesystem_state", "is_indexed")
    # ### end Alembic commands ###
