"""Initial schema

Revision ID: 9a6e70fabf7b
Revises:
Create Date: 2026-04-22 15:12:10.997643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a6e70fabf7b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filesystem_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("sha256_hash", sa.String(), nullable=True),
        sa.Column("last_seen_timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filesystem_state_file_path"),
        "filesystem_state",
        ["file_path"],
        unique=True,
    )
    op.create_index(
        op.f("ix_filesystem_state_sha256_hash"),
        "filesystem_state",
        ["sha256_hash"],
        unique=False,
    )
    op.create_table(
        "storage_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("generation_tier", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("bytes_used", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_media_identifier"),
        "storage_media",
        ["identifier"],
        unique=True,
    )
    op.create_table(
        "file_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filesystem_state_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("file_number", sa.String(), nullable=False),
        sa.Column("offset_in_tar", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["filesystem_state_id"],
            ["filesystem_state.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["storage_media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backup_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("log_level", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_logs")
    op.drop_table("file_versions")
    op.drop_index(op.f("ix_storage_media_identifier"), table_name="storage_media")
    op.drop_table("storage_media")
    op.drop_index(
        op.f("ix_filesystem_state_sha256_hash"), table_name="filesystem_state"
    )
    op.drop_index(op.f("ix_filesystem_state_file_path"), table_name="filesystem_state")
    op.drop_table("filesystem_state")
    op.drop_table("backups")
    # ### end Alembic commands ###
